
name: Kairead Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Compilar DragonTranslation
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Compilar extension
        run: |
          chmod +x ./gradlew
          ./gradlew :src:es:dragontranslationorg:assembleRelease

          
      - name: Guardar APK de DragonTranslation
        uses: actions/upload-artifact@v4
        with:
          name: Kairead-DragonTranslation
          path: |
           src/es/dragontranslationorg/build/outputs/**/*.apk
          if-no-files-found: error
          
